language: node_js

node_js:
  - '6'
  - '5'
  - '4'

before_script:
  - psql -U postgres < ./initdb.sql
  - cp ./config.example.js ./config.js

script:
  - npm test
  - npm run-script lint
  - npm run-script flow
